package utilities;

public enum ErrorCode {
    ERROR_MAX_CLIENT,
    ERROR_INVALID_POSITION,
    ERROR_WRONG_OPERATION,
    ERROR_PERMISSION_DENIED,
    ERROR_NOT_ENOUGH_MONEY,
    ERROR_OVERFLOW,
    ERROR_NO_MONOPOLY,
    ERROR_UNKNOWN_COMMAND
}
